name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Pull latest image
        run: sudo docker pull haritha564/nextora:latest

      - name: Remove old container
        run: sudo docker rm -f nextora || true

      - name: Run container (NO port 80)
        run: |
          sudo docker run -d \
            -p 127.0.0.1:3000:3000 \
            --restart unless-stopped \
            --name nextora \
            haritha564/nextora:latest
